language: elixir
elixir:
  - 1.1.0
otp_release:
  - 18.0

before_install:
  - git clone https://github.com/elixir-lang/elixir
  - cd elixir && make && cd ..
before_script: 
  - export PATH=`pwd`/elixir/bin:$PATH
  - copy config/typeform_secrets.exs.example config/typeform_secrets.exs

script:
  - "MIX_ENV=test mix do deps.get, compile, coveralls.travis"
